apiVersion: v1
kind: Service
metadata:
  name: {{ include "sus.fullname" . }}-landing
  namespace: {{ .Values.namespaces.platform }}
  labels:
    {{- include "sus.labels" . | nindent 4 }}
    app.kubernetes.io/component: landing
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "sus.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: landing
